const landingRoute = require('./routes/user/landing');
const authRoute = require('./routes/user/authRoute');
const authVendor = require('./routes/vendor/venderRoute');
const adminRoute = require('./routes/admin/authRoute');
const profileRoute = require('./routes/user/userProfile');
const fileRoute = require('./routes/admin/fileRoute');
const authProperty = require('./routes/user/property');
const authTender = require('./routes/user/tender');
const routerSearch = require('./routes/user/search');
const notification = require('./routes/user/notification');
const adminPropertyRoutes = require('./routes/admin/propertyRoute');
const adminTenderRoutes = require('./routes/admin/tenderRoute');
const adminContractRoutes = require('./routes/admin/contractManagemet');
const adminCouponRoutes = require('./routes/admin/couponManagement');
const userStatusRoutes = require('./routes/user/status');
const userProfileRoutes = require('./routes/user/myProfile');
const userListingRoutes = require('./routes/user/mylisting');
const userWalletRoutes = require('./routes/user/wallet');
const vendorTenderRoutes = require('./routes/vendor/tenderBId');
const vendorPostAwardRoutes = require('./routes/vendor/postAwardRoute');
const paymentRoutes = require('./routes/paymentRoute/payment');
const auctionRoutes = require('./routes/auction/liveAuction');
const chatRoute = require('./routes/chat/routerChat');

module.exports = function registerRoutes(app) {
  app.use('/', landingRoute);
  app.use('/auth', authRoute);
  app.use('/vendor', authVendor);
  app.use('/admin', adminRoute);
  app.use('/admin/file', fileRoute);
  app.use('/user', profileRoute);
  app.use('/properties', authProperty);
  app.use('/tenders', authTender);
  app.use('/search', routerSearch);
  app.use('/notifications', notification);
  app.use('/admin/property-management', adminPropertyRoutes);
  app.use('/admin/tender-management', adminTenderRoutes);
  app.use('/admin/contract-management', adminContractRoutes);
  app.use('/admin/coupon-management', adminCouponRoutes);
  app.use('/user/status', userStatusRoutes);
  app.use('/user/status', userProfileRoutes);
  app.use('/user/status/my-listing', userListingRoutes);
  app.use('/wallet', userWalletRoutes);
  app.use('/vendor/tender', vendorTenderRoutes);
  app.use('/publisher', vendorPostAwardRoutes);
  app.use('/payments', paymentRoutes);
  app.use('/auctions', auctionRoutes);
  app.use('/chat', chatRoute);
};
