const landingRoute = require('./user/landing');
const authRoute = require('./user/authRoute');
const authVendor = require('./vendor/venderRoute');
const adminRoute = require('./admin/authRoute');
const profileRoute = require('./user/userProfile');
const fileRoute = require('./admin/fileRoute');
const authProperty = require('./user/property');
const authTender = require('./user/tender');
const routerSearch = require('./user/search');
const notification = require('./user/notification');
const adminPropertyRoutes = require('./admin/propertyRoute');
const adminTenderRoutes = require('./admin/tenderRoute');
const adminContractRoutes = require('./admin/contractManagement');
const adminCouponRoutes = require('./admin/couponManagement');
const userStatusRoutes = require('./user/status');
const userProfileRoutes = require('./user/myProfile');
const userListingRoutes = require('./user/mylisting');
const userWalletRoutes = require('./user/wallet');
const vendorTenderRoutes = require('./vendor/tenderBId');
const vendorPostAwardRoutes = require('./vendor/postAwardRoute');
const paymentRoutes = require('./paymentRoute/payment');
const auctionRoutes = require('./auction/liveAuction');
const chatRoute = require('./chat/routerChat');
const workOrder = require('./vendor/workOrders');
const bidReportsRoute = require('./user/bidReports');
const adminBidReportsRoute = require('./admin/bidReports');
const adminTenderEvaluationRoute = require('./admin/tenderEvaluation');
const vendorTenderEvaluationRoute = require('./vendor/tenderEvaluation');
module.exports = function registerRoutes(app) {
  app.use('/', landingRoute);
  app.use('/auth', authRoute);
  app.use('/vendor', authVendor);
  app.use('/admin', adminRoute);
  app.use('/admin/file', fileRoute);
  app.use('/user/manage/my-listing', userListingRoutes);
  app.use('/user/manage', userStatusRoutes);
  app.use('/user/settings', userProfileRoutes);
  app.use('/user', profileRoute);
  app.use('/properties', authProperty);
  app.use('/tenders', authTender);
  app.use('/search', routerSearch);
  app.use('/notifications', notification);
  app.use('/wallet', userWalletRoutes);
  app.use('/payments', paymentRoutes);
  app.use('/auctions', auctionRoutes);
  app.use('/chat', chatRoute);
  app.use('/admin/property-management', adminPropertyRoutes);
  app.use('/admin/tender-management', adminTenderRoutes);
  app.use('/admin/contract-management', adminContractRoutes);
  app.use('/admin/coupon-management', adminCouponRoutes);
  app.use('/vendor/tender', vendorTenderRoutes);
  app.use('/publisher', vendorPostAwardRoutes);
  app.use('/', workOrder);
  app.use('/', bidReportsRoute);
  app.use('/', adminBidReportsRoute);
  app.use('/', adminTenderEvaluationRoute);
  app.use('/', vendorTenderEvaluationRoute);
};
