const { Transaction } = require('mongodb');

module.exports = {
  AUCTION_STATUS: {
    ENDED: 'ended',
    LIVE: 'live',
    NOT_STARTED: 'not_started',
  },
  PAYMENT_STATUS: {
    SUCCESS: 'success',
    PENDING: 'pending',
    FAILED: 'failed',
  },
  CONTEXT_TYPES: {
    PROPERTY: 'property',
    TENDER: 'tender',
  },
  PAYMENT_TYPES: {
    PARTICIPATION_FEE: 'participation_fee',
  },
  GATEWAYS: {
    RAZORPAY: 'razorpay',
    WALLET: 'wallet',
  },
  COUPON_TYPES: {
    FLAT: 'flat',
    PERCENT: 'percent',
  },
  BID_STATUS: {
    ACTIVE: 'active',
  },
  ROLES: {
    VENDOR: 'vendor',
  },
  APPLICATION_STATUS: {
    SUBMITTED: 'submitted',
  },
  TENDER_STATUS: {
    DRAFT: 'draft',
    SUBMITTED: 'submitted',
    PUBLISHED: 'published',
    REJECTED: 'rejected',
    CLOSED: 'closed',
  },
  ACTION_TYPES: {
    SCAN: 'scan',
  },
  ERROR_MESSAGES: {
    INVALID_AUCTION: 'INVALID_AUCTION',
    UNAUTHORIZED: 'UNAUTHORIZED',
    PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
    BID_TOO_LOW: 'BID_TOO_LOW',
    PROPERTY_NOT_FOUND: 'Property not found',
    TENDER_NOT_FOUND: 'Tender not found',
    SERVER_ERROR: 'Server error',
    PAYMENT_NOT_FOUND: 'Payment not found',
    INVALID_REQUEST: 'Invalid request',
    TENDER_RESTRICTED: 'This tender is not yet published or visible to you.',
    GENERIC_ERROR: 'Something went wrong',
    PAYMENT_FAILED: 'Payment failed: ',
    COUPON_REMOVE_FAILED: 'Failed to remove coupon: ',
    UPLOAD_REQUIRED: 'Please upload at least one document',
    CONFIRMATION_REQUIRED: 'Please confirm your details first',
    TERMS_REQUIRED: 'You must agree to the terms',
    FORBIDDEN_ACCESS: 'Forbidden: Access Denied',
    INVALID_CONTEXT_TYPE: 'Invalid context type',
    INVALID_PAYMENT: 'Invalid payment',
    SIGNATURE_FAILED: 'Signature verification failed',
    REMOVE_COUPON_FIRST: 'Please remove existing coupon first',
    INVALID_COUPON: 'Invalid coupon',
    COUPON_EXPIRED: 'Coupon expired',
    MIN_PURCHASE_NOT_MET: 'Minimum purchase not met',
    COUPON_ALREADY_USED: 'Coupon already used',
    CANNOT_MODIFY_COMPLETED: 'Cannot modify completed payment',
    NO_COUPON_APPLIED: 'No coupon applied',
    AUCTION_NOT_ENDED: 'Auction not ended yet',
    NO_BIDS_FOUND: 'No bids found',
    NOT_WINNER: 'You are not the winner',
    LOAD_RESULT_FAILED: 'Unable to load auction result',
    CONTRACT_NOT_FOUND: 'Contract not found',
    FILE_NOT_FOUND: 'File not found',
    INVALID_FILE_ID: 'Invalid file id',
    PROPERTY_ID_MISSING: 'Property ID missing',
    LOAD_TENDERS_FAILED: 'Failed to load tenders',
    INVALID_STATUS: 'Invalid status value',
    USER_ID_REQUIRED: 'User ID is required',
    VENDOR_NOT_FOUND: 'Vendor not found',
    LOAD_VENDOR_FAILED: 'Unable to load vendor',
    APPROVE_FAILED: 'Approve failed',
    REJECT_FAILED: 'Reject failed',
    REMOVE_FAILED: 'Failed to remove vendor',
    COUPON_REQUIRED_FIELDS: 'Coupon code, type and value are required',
    COUPON_EXISTS: 'Coupon code already exists',
    INVALID_DATE_RANGE: 'Start date cannot be after expiry date',
    COUPON_LIMIT_REACHED: 'Coupon usage limit reached',
    COUPON_FULLY_REDEEMED: 'Coupon fully redeemed',
    TRANSACTION_NOT_FOUND: 'Transaction not found',
  },
  SUCCESS_MESSAGES: {
    PAYMENT_SUCCESSFUL: 'Payment successful',
    COUPON_REMOVED: 'Coupon removed successfully',
    TENDER_RESUBMITTED: 'Tender re-submitted successfully 🎉',
    OCR_COMPLETED: 'OCR scan completed! Please confirm & submit',
    APPLICATION_SUBMITTED: 'Application submitted successfully!',
    ADMIN_LOGIN_SUCCESS: 'Admin logged in successfully',
    USER_BLOCKED: 'User Blocked Successfully',
    USER_UNBLOCKED: 'User unblocked successfully',
    COUPON_CREATED: 'Coupon created successfully',
    COUPON_APPLIED: 'Coupon applied successfully',
    PROPERTY_APPROVED: 'Property approved & published',
    PROPERTY_REJECTED: 'Property rejected',
    STATUS_UPDATED: 'Tender status updated',
    REVIEW_STARTED: 'Review started',
    VENDOR_APPROVED: 'Vendor approved',
    VENDOR_REJECTED: 'Vendor rejected',
    VENDOR_REMOVED: 'Vendor access removed successfully',
    OTP_RESENT: 'OTP is being resent',
  },
  VIEWS: {
    LIVE_AUCTION: 'acution/liveAuction',
    PUBLISHER_VIEW: 'acution/publisherView',
    ENABLE_AUTO_BID: 'acution/enableAutoBid',
    ERROR: 'error',
    ESCROW_PAYMENT: 'payments/escrowPayment',
    PAYMENT_SUCCESS: 'payments/paymentSuccess',
    PAYMENT_FAILS: 'payments/paymentFails',
    TENDER_LISTING: 'user/tender',
    TENDER_DETAILS: 'user/tenderDetails',
    VENDOR_APPLICATION: 'vendor/vendorApplication',
    AUCTION_RESULT_PUBLISHER: 'acution/result',
    AUCTION_RESULT_BUYER: 'acution/buyerWon',
    ADMIN_LOGIN: 'admin/login',
    ADMIN_DASHBOARD: 'admin/dahboard',
    ADMIN_USER_MANAGEMENT: 'admin/userManagement',
    ADMIN_CONTRACT_MANAGEMENT: 'admin/contractManagement',
    ADMIN_COUPON_MANAGEMENT: 'admin/couponManagement',
    ADMIN_PROPERTY_MANAGEMENT: 'admin/propertyManagement',
    ADMIN_AUCTION_VIEW: 'admin/adminAucationviewPage',
    ADMIN_TENDER_MANAGEMENT: 'admin/tenderManagement',
    ADMIN_VENDOR_LIST: 'admin/vendorList',
    USER_SIGNUP: 'user/signup',
    USER_LOGIN: 'user/login',
    USER_OTP: 'user/otp',
    USER_FORGOT_PASSWORD: 'user/forgotPassword',
    USER_RESET_PASSWORD: 'user/resetPassword',
    USER_DASHBOARD: 'user/dashboard',
    LANDING_PAGE: 'landingPage',
  },
  LAYOUTS: {
    USER_LAYOUT: 'layouts/user/userLayout',
    ADMIN_LAYOUT: 'layouts/admin/adminLayout',
  },
  REDIRECTS: {
    DASHBOARD: '/dashboard',
    PROPERTIES: '/properties',
    MY_PARTICIPATION: '/user/my-participation',
    PAYMENT_FAILURE: '/payments/failure',
    LOGIN: '/auth/login',
    AUTH_DASHBOARD: '/auth/dashboard',
    VENDOR_APPLY: '/vendor/apply',
    MY_BIDS: '/my-bids',
    ADMIN_DASHBOARD: '/admin/dashboard',
    ADMIN_LOGIN: '/admin/login',
    ADMIN_PROPERTY_MANAGEMENT: '/admin/property-management',
    SIGNUP: '/auth/signup',
    FORGOT_PASSWORD: '/auth/forgot-password',
  },
  ROUTES: {
    AUCTION_WON: '/auctions/won',
    AUCTION_RESULT: '/auctions/auction-result',
    AUCTION_LIVE: '/auctions/live',
    PAYMENT_INITIATE: '/payments/initiate',
    PAYMENT_ESCROW: '/payments/escrow',
    PAYMENT_SUCCESS: '/payments/success',
    PAYMENT_FAILURE: '/payments/failure',
  },
  ERROR_CODES: {
    TENDER_DRAFT: 'TENDER_DRAFT',
  },
  DEFAULTS: {
    PAGE: 1,
  },
  NOTIFICATION_MESSAGES: {
    TENDER_PUBLISHED: 'Your tender has been approved & published 🎉',
    TENDER_REJECTED: 'Your tender has been rejected ❌',
    TENDER_CLOSED: 'Your tender has been closed 🚫',
    VENDOR_APPROVED_SUBJECT: 'Vendor Application Approved 🎉',
    VENDOR_REJECTED_SUBJECT: 'Vendor Application Rejected ❌',
  },
};
