module.exports = {
  AUCTION_STATUS: {
    ENDED: 'ended',
    LIVE: 'live',
    NOT_STARTED: 'not_started',
  },
  PAYMENT_STATUS: {
    SUCCESS: 'success',
    PENDING: 'pending',
    FAILED: 'failed',
  },
  CONTEXT_TYPES: {
    PROPERTY: 'property',
    TENDER: 'tender',
  },
  PAYMENT_TYPES: {
    PARTICIPATION_FEE: 'participation_fee',
  },
  GATEWAYS: {
    RAZORPAY: 'razorpay',
    WALLET: 'wallet',
  },
  COUPON_TYPES: {
    FLAT: 'flat',
    PERCENT: 'percent',
  },
  BID_STATUS: {
    ACTIVE: 'active',
  },
  ROLES: {
    VENDOR: 'vendor',
  },
  APPLICATION_STATUS: {
    SUBMITTED: 'submitted',
    DRAFT: 'draft',
    APPROVED: 'approved',
    REJECTED: 'rejected',
    PENDING: 'pending', 
  },
  TENDER_STATUS: {
    DRAFT: 'draft',
    SUBMITTED: 'submitted',
    PUBLISHED: 'published',
    REJECTED: 'rejected',
    CLOSED: 'closed',
  },
  ACTION_TYPES: {
    SCAN: 'scan',
  },
  ERROR_MESSAGES: {
    INVALID_APPLICATION_STATE: 'INVALID_APPLICATION_STATE',
    INVALID_AUCTION: 'INVALID_AUCTION',
    UNAUTHORIZED: 'UNAUTHORIZED',
    PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
    BID_TOO_LOW: 'BID_TOO_LOW',
    PROPERTY_NOT_FOUND: 'Property not found',
    TENDER_NOT_FOUND: 'Tender not found',
    SERVER_ERROR: 'Server error',
    PAYMENT_NOT_FOUND: 'Payment not found',
    INVALID_REQUEST: 'Invalid request',
    TENDER_RESTRICTED: 'This tender is not yet published or visible to you.',
    GENERIC_ERROR: 'Something went wrong',
    PAYMENT_FAILED: 'Payment failed: ',
    COUPON_REMOVE_FAILED: 'Failed to remove coupon: ',
    UPLOAD_REQUIRED: 'Please upload at least one document',
    CONFIRMATION_REQUIRED: 'Please confirm your details first',
    TERMS_REQUIRED: 'You must agree to the terms',
    FORBIDDEN_ACCESS: 'Forbidden: Access Denied',
    INVALID_CONTEXT_TYPE: 'Invalid context type',
    INVALID_PAYMENT: 'Invalid payment',
    SIGNATURE_FAILED: 'Signature verification failed',
    REMOVE_COUPON_FIRST: 'Please remove existing coupon first',
    INVALID_COUPON: 'Invalid coupon',
    COUPON_EXPIRED: 'Coupon expired',
    MIN_PURCHASE_NOT_MET: 'Minimum purchase not met',
    COUPON_ALREADY_USED: 'Coupon already used',
    CANNOT_MODIFY_COMPLETED: 'Cannot modify completed payment',
    NO_COUPON_APPLIED: 'No coupon applied',
    AUCTION_NOT_ENDED: 'Auction not ended yet',
    NO_BIDS_FOUND: 'No bids found',
    NOT_WINNER: 'You are not the winner',
    LOAD_RESULT_FAILED: 'Unable to load auction result',
    CONTRACT_NOT_FOUND: 'Contract not found',
    FILE_NOT_FOUND: 'File not found',
    INVALID_FILE_ID: 'Invalid file id',
    PROPERTY_ID_MISSING: 'Property ID missing',
    LOAD_TENDERS_FAILED: 'Failed to load tenders',
    INVALID_STATUS: 'Invalid status value',
    USER_ID_REQUIRED: 'User ID is required',
    VENDOR_NOT_FOUND: 'Vendor not found',
    LOAD_VENDOR_FAILED: 'Unable to load vendor',
    APPROVE_FAILED: 'Approve failed',
    REJECT_FAILED: 'Reject failed',
    REMOVE_FAILED: 'Failed to remove vendor',
    COUPON_REQUIRED_FIELDS: 'Coupon code, type and value are required',
    COUPON_EXISTS: 'Coupon code already exists',
    INVALID_DATE_RANGE: 'Start date cannot be after expiry date',
    COUPON_LIMIT_REACHED: 'Coupon usage limit reached',
    COUPON_FULLY_REDEEMED: 'Coupon fully redeemed',
    TRANSACTION_NOT_FOUND: 'Transaction not found',
    ERROR_LOADING_TENDER_PAGE: 'Error loading tender page',
    PROPERTY_ALREADY_EXISTS: 'A similar property already exists in the system.',
    UNABLE_LOAD_TENDER_STATUS: 'Unable to load tender status',
    TENDER_NOT_FOUND_UNAUTHORIZED: 'Tender not found or unauthorized',
    SERVER_ERROR_DELETING_TENDER: 'Server error deleting tender',
    FAILED_FETCH_BALANCE: 'Failed to fetch balance',
    MINIMUM_AMOUNT_REQUIRED: 'Minimum amount is ₹100',
    PAYMENT_GATEWAY_NOT_CONFIGURED: 'Payment gateway not configured. Please contact support.',
    PAYMENT_VERIFICATION_FAILED: 'Payment verification failed',
    ALL_FIELDS_REQUIRED: 'All field require',
    PROFILE_UPDATED: 'Profile updated',
    UNABLE_LOAD_LISTINGS: 'Unable to load listings',
    PO_NOT_FOUND: 'PO not found',
    NO_FILE_UPLOADED: 'No file uploaded',
    ERROR_UPLOADING_AGREEMENT: 'Error uploading agreement',
    USER_NOT_FOUND: 'user not found',
    ACCESS_DENIED: 'access denined',
    WINNER_VENDOR_NOT_FOUND: 'Winner vendor not found',
    UPLOAD_FAILED: 'Upload failed',
    UNABLE_OPEN_FILE: 'Unable to open file',
    APPROVAL_FAILED: 'Approval failed',
    WORK_ORDER_NOT_FOUND: 'Work order not found',
    NOT_A_VENDOR: 'Not a vendor',
    PAGE_NOT_FOUND: 'The page you are looking for does not exist.',
    TOO_MANY_REQUESTS: '⚠️ Too many requests. Please wait 1 minute.',
    ONLY_VERIFIED_VENDOR_CREATE_TENDER: 'Only Verified Vendor Can Create A Tender',
    TENDER_TITLE_REQUIRED: 'Tender title is required',
    DEPARTMENT_REQUIRED: 'Department is required',
    CATEGORY_REQUIRED: 'Category is required',
    BID_END_DATE_REQUIRED: 'Bid end date is required',
    DUPLICATE_TENDER_DOCUMENT: 'Duplicate Tender Document! Upload unique files.',
    EMAIL_NOT_FOUND: 'Email not found',
    ADMIN_BLOCKED: 'Admin Blocked! Please contact Admin',
    VERIFY_OTP_FIRST: 'Please verify your OTP first',
    INVALID_PASSWORD: 'Invalid Password',
    OTP_EXPIRED_NOT_FOUND: 'OTP expired or not found',
    PASSWORD_NOT_CORRECT: 'Password not currect',
    USER_ID_REQUIRED_SERVICE: 'userId is required',
    ADMIN_NOT_FOUND: 'Admin not found',
    INVALID_CREDENTIALS: 'Invalid credentials',
    FAILED_LOAD_DASHBOARD_STATS: 'failed to load dashboard stats',
    ACCOUNT_BLOCKED_BY_ADMIN: 'Your account has been blocked by admin',
    UPLOAD_AT_LEAST_ONE_DOC: 'Upload at least 1 document',
    DUPLICATE_DOCUMENT: 'Duplicate document detected! Please upload a different file.',
    CANNOT_RUN_OCR: 'Cannot run OCR — no valid document uploaded.',
    NOT_VENDOR: 'NOT_VENDOR',
    ALREADY_UPLOADED: 'ALREADY_UPLOADED',
    NO_BID: 'NO_BID',
    TECH_REJECTED: 'TECH_REJECTED',
    TECH_NOT_APPROVED: 'TECH_NOT_APPROVED',
    NO_WINNER_FOUND: 'NO_WINNER_FOUND',
    NO_FILE: 'NO_FILE',
    WINNER_NOT_FOUND: 'WINNER_NOT_FOUND',
    AGREEMENT_NOT_FOUND: 'AGREEMENT_NOT_FOUND',
    WORK_ORDER_ALREADY_ISSUED: 'WORK_ORDER_ALREADY_ISSUED',
    WORK_ORDER_PDF_REQUIRED: 'WORK_ORDER_PDF_REQUIRED',
    WORK_ORDER_DESCRIPTION_REQUIRED: 'WORK_ORDER_DESCRIPTION_REQUIRED',
    FILE_URL_MISSING: 'FILE_URL_MISSING',
    PO_ALREADY_ACCEPTED: 'PO_ALREADY_ACCEPTED',
    PO_ALREADY_EXISTS: 'PO_ALREADY_EXISTS',
    PO_NOT_CREATED: 'PO_NOT_CREATED',
    PO_NOT_ACCEPTED: 'PO_NOT_ACCEPTED',
    PUBLISHER_AGREEMENT_NOT_FOUND: 'PUBLISHER_AGREEMENT_NOT_FOUND',
    NOT_PARTICIPATED: 'NOT_PARTICIPATED',
    INVALID_ACTION: 'INVALID_ACTION',
    BID_NOT_FOUND: 'BID_NOT_FOUND',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    PHONE_ALREADY_EXISTS: 'Phone already exists',
    EMAIL_ALREADY_EXISTS: 'Email already exists',
  },
  SUCCESS_MESSAGES: {
    PAYMENT_SUCCESSFUL: 'Payment successful',
    COUPON_REMOVED: 'Coupon removed successfully',
    TENDER_RESUBMITTED: 'Tender re-submitted successfully 🎉',
    OCR_COMPLETED: 'OCR scan completed! Please confirm & submit',
    APPLICATION_SUBMITTED: 'Application submitted successfully!',
    ADMIN_LOGIN_SUCCESS: 'Admin logged in successfully',
    USER_BLOCKED: 'User Blocked Successfully',
    USER_UNBLOCKED: 'User unblocked successfully',
    COUPON_CREATED: 'Coupon created successfully',
    COUPON_APPLIED: 'Coupon applied successfully',
    PROPERTY_APPROVED: 'Property approved & published',
    PROPERTY_REJECTED: 'Property rejected',
    STATUS_UPDATED: 'Tender status updated',
    REVIEW_STARTED: 'Review started',
    VENDOR_APPROVED: 'Vendor approved',
    VENDOR_REJECTED: 'Vendor rejected',
    VENDOR_REMOVED: 'Vendor access removed successfully',
    OTP_RESENT: 'OTP is being resent',
    TENDER_CREATED: 'Tender created successfully',
    PROPERTY_SUBMITTED: 'Property submitted successfully. It will be visible after admin approval.',
    PROPERTY_UPDATED: 'Property updated successfully',
    DOCUMENT_REMOVED: 'Document removed successfully',
    IMAGE_REMOVED: 'Image removed successfully',
    TENDER_DELETED: 'Tender deleted successfully',
    PASSWORD_CHANGED: 'Password Change is successfull',
    PROFILE_UPDATED_SUCCESS: 'Profile updated',
    OTP_SENT_SUCCESS: 'OTP sent successfully',
    ACCOUNT_VERIFIED: 'Account Verified Successfully 🎉',
    LOGIN_SUCCESS: 'Login successful 🎉',
    OTP_SENT_EMAIL: 'OTP send to your email',
    OTP_VERIFIED_SUCCESS: 'OTP Verified Successfully',
    PASSWORD_RESET_SUCCESS: 'Password reset successfully',
    NEW_OTP_SENT: 'New OTP sent to your email',
  },
  VIEWS: {
    LIVE_AUCTION: 'acution/liveAuction',
    PUBLISHER_VIEW: 'acution/publisherView',
    ENABLE_AUTO_BID: 'acution/enableAutoBid',
    ERROR: 'error',
    ESCROW_PAYMENT: 'payments/escrowPayment',
    PAYMENT_SUCCESS: 'payments/paymentSuccess',
    PAYMENT_FAILS: 'payments/paymentFails',
    TENDER_LISTING: 'user/tender',
    TENDER_DETAILS: 'user/tenderDetails',
    VENDOR_APPLICATION: 'vendor/vendorApplication',
    AUCTION_RESULT_PUBLISHER: 'acution/result',
    AUCTION_RESULT_BUYER: 'acution/buyerWon',
    ADMIN_LOGIN: 'admin/login',
    ADMIN_DASHBOARD: 'admin/dahboard',
    ADMIN_USER_MANAGEMENT: 'admin/userManagement',
    ADMIN_CONTRACT_MANAGEMENT: 'admin/contractManagement',
    ADMIN_COUPON_MANAGEMENT: 'admin/couponManagement',
    ADMIN_PROPERTY_MANAGEMENT: 'admin/propertyManagement',
    ADMIN_AUCTION_VIEW: 'admin/adminAucationviewPage',
    ADMIN_TENDER_MANAGEMENT: 'admin/tenderManagement',
    ADMIN_VENDOR_LIST: 'admin/vendorList',
    USER_SIGNUP: 'user/signup',
    USER_LOGIN: 'user/login',
    USER_OTP: 'user/otp',
    USER_FORGOT_PASSWORD: 'user/forgotPassword',
    USER_RESET_PASSWORD: 'user/resetPassword',
    USER_DASHBOARD: 'user/dashboard',
    LANDING_PAGE: 'landingPage',
  },
  LAYOUTS: {
    USER_LAYOUT: 'layouts/user/userLayout',
    ADMIN_LAYOUT: 'layouts/admin/adminLayout',
  },
  REDIRECTS: {
    DASHBOARD: '/dashboard',
    PROPERTIES: '/properties',
    MY_PARTICIPATION: '/user/my-participation',
    PAYMENT_FAILURE: '/payments/failure',
    LOGIN: '/auth/login',
    AUTH_DASHBOARD: '/auth/dashboard',
    VENDOR_APPLY: '/vendor/apply',
    MY_BIDS: '/my-bids',
    ADMIN_DASHBOARD: '/admin/dashboard',
    ADMIN_LOGIN: '/admin/login',
    ADMIN_PROPERTY_MANAGEMENT: '/admin/property-management',
    SIGNUP: '/auth/signup',
    FORGOT_PASSWORD: '/auth/forgot-password',
  },
  ROUTES: {
    AUCTION_WON: '/auctions/won',
    AUCTION_RESULT: '/auctions/auction-result',
    AUCTION_LIVE: '/auctions/live',
    PAYMENT_INITIATE: '/payments/initiate',
    PAYMENT_ESCROW: '/payments/escrow',
    PAYMENT_SUCCESS: '/payments/success',
    PAYMENT_FAILURE: '/payments/failure',
  },
  ERROR_CODES: {
    TENDER_DRAFT: 'TENDER_DRAFT',
  },
  DEFAULTS: {
    PAGE: 1,
  },
  NOTIFICATION_MESSAGES: {
    TENDER_PUBLISHED: 'Your tender has been approved & published 🎉',
    TENDER_REJECTED: 'Your tender has been rejected ❌',
    TENDER_CLOSED: 'Your tender has been closed 🚫',
    VENDOR_APPROVED_SUBJECT: 'Vendor Application Approved 🎉',
    VENDOR_REJECTED_SUBJECT: 'Vendor Application Rejected ❌',
  },
  COUPON_MESSAGES: {
    MISSING_FIELDS: 'MISSING_FIELDS',
    COUPON_EXISTS: 'COUPON_EXISTS',
    INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
    NOT_FOUND: 'NOT_FOUND',
    INVALID_COUPON: 'INVALID_COUPON',
    COUPON_EXPIRED: 'COUPON_EXPIRED',
    COUPON_LIMIT_REACHED: 'COUPON_LIMIT_REACHED',
    COUPON_FULLY_REDEEMED: 'COUPON_FULLY_REDEEMED',
  },
  VALIDATION_MESSAGES: {
    PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
    CONFIRM_BUSINESS_DETAILS: 'You must confirm your business details',
    ACCEPT_TERMS: 'You must accept the terms',
  },
};
