require('dotenv').config();
const mongoose = require('mongoose');
const Property = require('./models/property');

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);

  // await Property.deleteMany({}); // optional clean

  const sellerId = new mongoose.Types.ObjectId('69454fa7548483e03b35c812');

  const properties = [
    {
      sellerId,
      title: '3 BHK Premium Villa',
      description: 'Independent luxury villa with garden & parking',
      type: 'house',
      address: 'Kayamkulam, Alappuzha',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.1826,
      geoLng: 76.5317,
      bhk: 3,
      size: 1850,
      isAuction: true,
      basePrice: 5500000,
      auctionStep: 25000,
      auctionReservePrice: 6000000,
      auctionStartsAt: new Date('2026-01-10T10:00:00Z'),
      auctionEndsAt: new Date('2026-01-15T16:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
    {
      sellerId,
      title: 'Commercial Highway Plot',
      description: 'Roadside commercial land',
      type: 'commercial',
      address: 'NH 66, Kayamkulam',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.1865,
      geoLng: 76.5341,
      size: 3200,
      isAuction: true,
      basePrice: 7200000,
      auctionStep: 50000,
      auctionReservePrice: 8000000,
      auctionStartsAt: new Date('2026-01-12T09:00:00Z'),
      auctionEndsAt: new Date('2026-01-18T17:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1502005097973-6a7082348e28' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
    {
      sellerId,
      title: '2 BHK Lake View Apartment',
      description: 'Apartment facing Kayamkulam lake',
      type: 'apartment',
      address: 'Kayamkulam Lake Road',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.1841,
      geoLng: 76.5302,
      bhk: 2,
      size: 1250,
      isAuction: true,
      basePrice: 4200000,
      auctionStep: 20000,
      auctionReservePrice: 4700000,
      auctionStartsAt: new Date('2026-01-08T09:30:00Z'),
      auctionEndsAt: new Date('2026-01-13T16:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
    {
      sellerId,
      title: 'Modern Duplex House',
      description: 'Newly built duplex home',
      type: 'house',
      address: 'Haripad',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.2584,
      geoLng: 76.4647,
      bhk: 4,
      size: 2100,
      isAuction: true,
      basePrice: 6800000,
      auctionStep: 30000,
      auctionReservePrice: 7500000,
      auctionStartsAt: new Date('2026-01-14T10:00:00Z'),
      auctionEndsAt: new Date('2026-01-20T16:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1560185127-6ed189bf02a4' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
    {
      sellerId,
      title: 'Beach Side Cottage',
      description: 'Cottage near Alappuzha beach',
      type: 'house',
      address: 'Alappuzha Beach',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.4947,
      geoLng: 76.3274,
      bhk: 2,
      size: 950,
      isAuction: true,
      basePrice: 5000000,
      auctionStep: 20000,
      auctionReservePrice: 5500000,
      auctionStartsAt: new Date('2026-01-09T10:00:00Z'),
      auctionEndsAt: new Date('2026-01-14T16:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
    {
      sellerId,
      title: 'Hill View Land',
      description: 'Scenic hill facing land',
      type: 'land',
      address: 'Mavelikara',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.2667,
      geoLng: 76.5589,
      size: 5400,
      isAuction: true,
      basePrice: 3800000,
      auctionStep: 15000,
      auctionReservePrice: 4200000,
      auctionStartsAt: new Date('2026-01-11T09:00:00Z'),
      auctionEndsAt: new Date('2026-01-16T16:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
    {
      sellerId,
      title: 'City Center Shop',
      description: 'Retail shop in city center',
      type: 'commercial',
      address: 'Alappuzha Town',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.4981,
      geoLng: 76.3388,
      size: 600,
      isAuction: true,
      basePrice: 2500000,
      auctionStep: 10000,
      auctionReservePrice: 2800000,
      auctionStartsAt: new Date('2026-01-10T09:00:00Z'),
      auctionEndsAt: new Date('2026-01-15T16:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
    {
      sellerId,
      title: 'Farm Land Plot',
      description: 'Agricultural land',
      type: 'land',
      address: 'Chengannur',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.3185,
      geoLng: 76.6151,
      size: 7000,
      isAuction: true,
      basePrice: 3000000,
      auctionStep: 15000,
      auctionReservePrice: 3400000,
      auctionStartsAt: new Date('2026-01-13T09:00:00Z'),
      auctionEndsAt: new Date('2026-01-19T16:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
    {
      sellerId,
      title: 'Luxury Penthouse',
      description: 'Top floor penthouse with lake view',
      type: 'apartment',
      address: 'Kuttanad',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.3875,
      geoLng: 76.4175,
      bhk: 3,
      size: 1900,
      isAuction: true,
      basePrice: 9000000,
      auctionStep: 40000,
      auctionReservePrice: 9800000,
      auctionStartsAt: new Date('2026-01-14T09:00:00Z'),
      auctionEndsAt: new Date('2026-01-21T16:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1598928506311-c55dedb3c6f0' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
    {
      sellerId,
      title: 'Warehouse Godown',
      description: 'Large warehouse near NH',
      type: 'commercial',
      address: 'Ambalappuzha',
      locationState: 'Kerala',
      locationDistrict: 'Alappuzha',
      geoLat: 9.3892,
      geoLng: 76.3401,
      size: 5000,
      isAuction: true,
      basePrice: 6500000,
      auctionStep: 30000,
      auctionReservePrice: 7200000,
      auctionStartsAt: new Date('2026-01-15T09:00:00Z'),
      auctionEndsAt: new Date('2026-01-22T16:00:00Z'),
      media: [{ url: 'https://images.unsplash.com/photo-1581091870627-3f92f8f47bb1' }],
      docs: [{ url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf' }],
      status: 'published',
      verificationStatus: 'approved',
      verificationRequestedAt: new Date(),
    },
  ];

  await Property.insertMany(properties);
  console.log('✅ 10 Properties seeded successfully');
  process.exit();
}

seed();
